//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuOsk {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RuOsk.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuOsk.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEAR.
        /// </summary>
        internal static string btnClearLong {
            get {
                return ResourceManager.GetString("btnClearLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLR.
        /// </summary>
        internal static string btnClearShort {
            get {
                return ResourceManager.GetString("btnClearShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY.
        /// </summary>
        internal static string btnCopyLong {
            get {
                return ResourceManager.GetString("btnCopyLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CP.
        /// </summary>
        internal static string btnCopyShort {
            get {
                return ResourceManager.GetString("btnCopyShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUT.
        /// </summary>
        internal static string btnCutLong {
            get {
                return ResourceManager.GetString("btnCutLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIDE.
        /// </summary>
        internal static string btnToggleHide {
            get {
                return ResourceManager.GetString("btnToggleHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHOW.
        /// </summary>
        internal static string btnToggleShow {
            get {
                return ResourceManager.GetString("btnToggleShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPY TRANSLIT.
        /// </summary>
        internal static string btnTranslitLong {
            get {
                return ResourceManager.GetString("btnTranslitLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CT.
        /// </summary>
        internal static string btnTranslitShort {
            get {
                return ResourceManager.GetString("btnTranslitShort", resourceCulture);
            }
        }
    }
}
